export default {
    FETCH_ALL_GATEWAYS: "FETCH_ALL_GATEWAYS",
    REMOVE_GATEWAY: "REMOVE_GATEWAY",
    ADD_GATEWAY: "ADD_GATEWAY",
    ADD_DEVICE: "ADD_DEVICE",
    REMOVE_DEVICE: "REMOVE_DEVICE"
};
